name: tabmaker_dart
description: A utility for turning easy-to-write tabs into markdown.
version: 0.0.1
repository: https://github.com/chrisnorman7/tabmaker_dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.3
  test_process: ^2.0.2

executables:
  tabmaker: tabmekr_dart
